name: shaur_chat_app
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.0-47.0.dev <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutterfire_ui: ^0.4.3+4
  firebase_core: ^1.20.0
  firebase_auth: ^3.6.2
  contacts_service: ^0.6.3
  flutter_contacts: ^1.1.5
  url_launcher: ^6.1.5
  fluttertoast: ^8.0.9
  cloud_firestore: ^3.4.5
  intl: ^0.17.0
  flutter_speed_dial: ^6.0.0
  firebase_storage: ^10.3.7
  file_picker: ^5.0.1
  regexed_validator: ^2.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/logo/
    - assets/images/