// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIioKwW71-Acrm3NxuM8TQoUa0VeO1Jp4',
    appId: '1:325591603918:web:1cf4f6a98687deebff0e9f',
    messagingSenderId: '325591603918',
    projectId: 'shaur-chat',
    authDomain: 'shaur-chat.firebaseapp.com',
    storageBucket: 'shaur-chat.appspot.com',
    measurementId: 'G-63YKMJW2JY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8X-czak1dy1qY4LzSz2UbFD55WBeNuuo',
    appId: '1:325591603918:android:c564cb68a11782b7ff0e9f',
    messagingSenderId: '325591603918',
    projectId: 'shaur-chat',
    storageBucket: 'shaur-chat.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyy05xyGzF-_A9GVVXa7V0u1TwaSfz7W0',
    appId: '1:325591603918:ios:813d18e0d8f53818ff0e9f',
    messagingSenderId: '325591603918',
    projectId: 'shaur-chat',
    storageBucket: 'shaur-chat.appspot.com',
    androidClientId: '325591603918-ctcqh7basj9ht9adeqae89f1ghs2gvsl.apps.googleusercontent.com',
    iosClientId: '325591603918-ttgb3up3iqbvmtrgup0jdheo8hd2hatb.apps.googleusercontent.com',
    iosBundleId: 'com.example.shaurSec',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyy05xyGzF-_A9GVVXa7V0u1TwaSfz7W0',
    appId: '1:325591603918:ios:813d18e0d8f53818ff0e9f',
    messagingSenderId: '325591603918',
    projectId: 'shaur-chat',
    storageBucket: 'shaur-chat.appspot.com',
    androidClientId: '325591603918-ctcqh7basj9ht9adeqae89f1ghs2gvsl.apps.googleusercontent.com',
    iosClientId: '325591603918-ttgb3up3iqbvmtrgup0jdheo8hd2hatb.apps.googleusercontent.com',
    iosBundleId: 'com.example.shaurSec',
  );
}
